import { LitElement } from "lit";
import { GraphController } from "../controllers/graph-controller";
import { GraphState } from "../models/graph-model";
import { AppController } from "../controllers/app-controller";
import { AppState } from "../models/app-model";
import { StringMatchDictionaryItem } from "../workers/string-match";
import "@spectrum-web-components/theme/sp-theme.js";
import "@spectrum-web-components/theme/scale-medium.js";
import "@spectrum-web-components/theme/theme-darkest.js";
import "@spectrum-web-components/theme/theme-light.js";
import "@spectrum-web-components/toast/sp-toast.js";
import "./token-graph";
import "./stvt-sidebar";
import "./stvt-hud";
export declare class StvtApp extends LitElement {
  graphState: GraphState;
  appState: AppState;
  dictionary: StringMatchDictionaryItem[];
  showAlert: boolean;
  alertMessage: string;
  alertKey: string;
  graphController: GraphController;
  appController: AppController;
  urlParamComponent: string;
  urlParamToken: string;
  urlParamFilter: string;
  urlParams: URLSearchParams;
  static styles: import("lit").CSSResult;
  constructor();
  willUpdate(changedProperties: Map<string, unknown>): void;
  handleCopiedToClipboard(e: CustomEvent): Promise<void>;
  render(): import("lit-html").TemplateResult<1>;
}
