import { LitElement } from "lit";
import "@spectrum-web-components/action-button/sp-action-button.js";
import { Gesture, GestureEvent } from "../utilities/index";
type ValueTuple = [value: string, path: string];
export declare class TokenGraphNode extends LitElement {
  id: string;
  value: string;
  type: string;
  isFaded: boolean;
  isIntersect: boolean;
  selected: boolean;
  selectionAncestor: boolean;
  selectionDescendent: boolean;
  hasDownstream: boolean;
  hoverUpstream: boolean;
  gesture?: Gesture;
  isValidDrag: boolean;
  decomposedValues: ValueTuple[];
  rowCount: number;
  pointerOverDepth: number;
  isInteractingWithButton: boolean;
  fillColor: string;
  textColor: string;
  static styles: import("lit").CSSResult;
  willUpdate(changedProperties: Map<string, unknown>): void;
  preventDefault(e: any): boolean;
  handlePointerDownOnIcon(): void;
  handlePointerUpOnIcon(): void;
  handlePointerDown(e: PointerEvent): void;
  handlePointerOver(): void;
  handlePointerOut(): void;
  handleDragMove(e: GestureEvent): void;
  handleDragStart(e: GestureEvent): void;
  handleDragEnd(e: GestureEvent): void;
  handleClick(e: GestureEvent): void;
  handleSingleClick(e: GestureEvent): void;
  handleDoubleClick(e: GestureEvent): void;
  copyToClipboard(e: PointerEvent): void;
  get valueHtml(): import("lit-html").TemplateResult<1>;
  render(): import("lit-html").TemplateResult<1>;
}
export {};
